##The amount of minutes between mechanical dispatches
#The mechanical dispatch is checked every minute
#It only triggers if the amount of paladins who haven't been dispatched in {paladin-idle-time} mins is more than the open slots in ongoing emergencies
#(ignoring paladins who logged in less than {paladin-idle-time} mins ago)
#This cooldown is also triggered if an emergency expires without meeting its dispatch par, since this implies that they are spread too thin
paladin-idle-time: 20
mechanical-dispatch-cooldown: 20

##If you are within n blocks of an ongoing emergency, your report will do nothing
#this also controls the placeholder %sneakydispatch_nearby_emergency%
emergency-radius: 50

##The icon that is shown in the dispatch menu when an emergency has reached its cap
cap-icon-material: "red_wool"
cap-icon-custom-model-data: 0

##How the name of a paladin is shown in tooltips nad command feedback. Supports placeholders, and "[playerName]" replacement.
paladin-name-display: "%sneakycharacters_character_name_noformat%"

##Resolved once when an emergency is reported (PAPI if enabled). Use [locationString] in emergency descriptions.
location-string: "%dipp_district_name%"

##These are text replacements that occur on the emergency description if the emergency has been reported with a delay (that is to say, a scripted report rather than a manual one)
#These are applied BEFORE placeholder replacement
#These must be supplied as a string list, and one of the replacements will be chosen at random
delayed-tooltip-text-replacements:
  people:
    - locals
  person:
    - local
  citizen:
    - local
  "%sneakycharacters_character_name%":
    - A fisherman
    - A farmer
    - A dwarven miner
    - A store clerk
    - A dwarf
    - A baker
    - A sorcerer
    - A blacksmith
    - A lumberjack
    - An old ranger
    - A scoundrel
    - An old beggar
    - A artisan
    - A brewer
    - A chef
    - A cobbler
    - A dancer
    - A gardener
    - A musician
    - A painter
    - A poet
    - A sculptor
    - A tailor
    - A weaver
    - An ugly peasant
    - A kobold
    - A mysterious peasant
    - Someone named Jimmy
    - An elf
    - A butcher
    - A goat herder
    - A stablehand
    - A scholar
    - A priest
    - A sailor
    - A hunter
    - A trapper
    - A gravedigger
    - A herbalist
    - An alchemist
    - A muk trader
    - A merchant
    - A bard
    - A fortune teller
    - An offduty paladin
    - A monk
    - A druid
    - A mercenary
    - A gambler
    - A rat catcher
    - A mage
    - A peasant minding their own business
    - Another criminal
    - Doug
    - An off duty Paladin
    - A known liar
    - An untrustworthy peasant


##The dispatch-cap represents the maximum amount of paladins that we want to see at a scene
#This is visible to the players. Without proper permissions, it will be enforced.
##The dispatch-par represents the minimal amount of paladins that we want to see at a scene
#This is not visible to players. It is used behind the scenes to judge whether the paladins are spread too thin
##The descriptions support placeholder replacement and [locationString]. They use the reporting player for replacements, and are only parsed at the moment of reporting
emergencies:
    misc:
        name: "Call for Help"
        description: "%sneakycharacters_character_name% is in need of aid in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1313
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    backup:
        name: "Call for Backup"
        description: "%sneakycharacters_character_name% has called for backup in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1339
        dispatch-cap: 999
        dispatch-par: 0
        duration-milis: 600000
    crime:
        name: "Crime"
        description: "Lawbreakers are afoot in [locationString]! Stop them!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1197
        dispatch-cap: 2
        dispatch-par: 2
        duration-milis: 300000
    fire:
        name: "Fire"
        description: "%sneakycharacters_character_name% has reported a fire breaking out in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1033
        dispatch-cap: 999
        dispatch-par: 4
        duration-milis: 900000
    attack:
        name: "Monster Attack"
        description: "%sneakycharacters_character_name% has reported a Monster Attack in [locationString]! Suit up, Paladin!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1335
        dispatch-cap: 999
        dispatch-par: 4
        duration-milis: 900000
    hazard:
        name: "Hazardous Situation"
        description: "%sneakycharacters_character_name% has reported a hazardous situation in [locationString]! Protect the people!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1449
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    wildlife:
        name: "Wildlife Nuisance"
        description: "%sneakycharacters_character_name% has reported that wild animals are disturbing our way of life in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1148
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    mukburning:
        name: "Muk Burning"
        description: "%sneakycharacters_character_name% has reported that peasants are burning Muk in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1362
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    dynamite:
        name: "Dynamite Contrband"
        description: "&e%sneakycharacters_character_name% &7has reported that peasants are throwing &4Dynamite &7in &6[locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1033
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    necromancy:
        name: "Necromancy"
        description: "%sneakycharacters_character_name% has reported that peasants are ressurecting the dead in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1034
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    darkarts:
        name: "Dark Arts"
        description: "%sneakycharacters_character_name% has reported that peasants have been seen performing dark rituals in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1035
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    pickpocket:
        name: "Pickpocketing"
        description: "%sneakycharacters_character_name% has reported that peasants have been seen with sticky fingers in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1036
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    dragondust:
        name: "Dragon Dust"
        description: "%sneakycharacters_character_name% has reported a high crime of peasants consuming dragon dust in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1037
        dispatch-cap: 3
        dispatch-par: 1
        duration-milis: 300000
    egging:
        name: "Egging"
        description: "%sneakycharacters_character_name% has reported eggs being thrown in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1038
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    swammie:
        name: "Swammers"
        description: "%sneakycharacters_character_name% has reported people doing swams in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1190
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    counterfeit:
        name: "Counterfeits"
        description: "%sneakycharacters_character_name% has reported someone making fake money in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1190
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    burglery:
        name: "Burglery"
        description: "%sneakycharacters_character_name% has reported a burglery in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1244
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    drugdeal:
        name: "Drug Deal"
        description: "%sneakycharacters_character_name% has reported a drug deal going down in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1245
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    bricking:
        name: "Bricking"
        description: "%sneakycharacters_character_name% has reported windows being broken in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1246
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    manastealing:
        name: "Mana Stealing"
        description: "%sneakycharacters_character_name% has reported mana being stolen in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1248
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000
    shoplifting:
        name: "Shoplifting"
        description: "%sneakycharacters_character_name% has reported a shoplifting in [locationString]!"
        icon-material: "jigsaw"
        icon-custom-model-data: 1255
        dispatch-cap: 2
        dispatch-par: 1
        duration-milis: 300000