##The amount of minutes between encounters
#The encounter conditions is checked every minute
#It only triggers if the amount of paladins who haven't been dispatched in {paladin-idle-time} mins is more than the open slots in ongoing emergencies
#(ignoring paladins who logged in less than {paladin-idle-time} mins ago)
#This cooldown is also triggered if an emergency expires without meeting its dispatch par, since this implies that they are spread too thin
#Both values are in mins support a random value between a lower and an upper bound, separated by a dash (such as 15-30).
paladin-idle-time: 10-20
encounter-cooldown: 15-30

##After a paladin goes off duty, if their unit is now this size or lower, then the unit will disband.
unit-disband-size: 0

##If you are within n blocks of an ongoing emergency, your report will do nothing
#this also controls the placeholder %sneakydispatch_nearby_emergency%
emergency-radius: 50

##The icon that is shown in the dispatch menu when an emergency has reached its cap
cap-icon-material: "red_wool"
cap-icon-custom-model-data: 0

##How the names of the paladins designated to an encounter are shown in the item tooltip. Supports placeholders, and "[playerName]" replacement.
tooltip-paladin-name: "[playerName]"

##These are text replacements that occur on the emergency description if the emergency has been reported with a delay (that is to say, a scripted report rather than a manual one)
#These are applied BEFORE placeholder replacement
#These must be supplied as a string list, and one of the replacements will be chosen at random
delayed-tooltip-text-replacements:
  people:
    - locals
  person:
    - local
  citizen:
    - local
  "%sneakycharacters_character_name%":
    - a local fisherman
    - a local farmer
    - a local miner
    - a local store clerk
    - a local dwarf
    - a local baker
    - a local sorcerer
    - a local blacksmith
    - a local lumberjack
    - a local ranger
    - a local scoundrel
    - a local beggar
    - a local artisan
    - a local brewer
    - a local chef
    - a local cobbler
    - a local dancer
    - a local gardener
    - a local musician
    - a local painter
    - a local poet
    - a local sculptor
    - a local storyteller
    - a local tailor
    - a local weaver

##The dispatch-cap represents the maximum amount of paladins that we want to see at a scene
#This is visible to the players. This will not be enforced, but it is used to determine the current open dispatch slots by the pacing controller.
##The dispatch-par represents the minimal amount of paladins that we want to see at a scene
#This is not visible to players. It is used behind the scenes to judge whether the paladins are spread too thin
##The descriptions support placeholder replacement. They use the reporting player for replacements, and are only parsed at the moment of reporting
emergencies:
    misc:
        name: "Call for Help"
        description: "%sneakycharacters_character_name% is in need of aid in %dipp_district_name%!"
        icon-material: "music_disc_cat"
        icon-custom-model-data: 1
        dispatch-cap: 2
        dispatch-par: 1
        duration-millis: 600000
    backup:
        name: "Call for Backup"
        description: "%sneakycharacters_character_name% has called for backup in %dipp_district_name%!"
        icon-material: "music_disc_cat"
        icon-custom-model-data: 1
        dispatch-cap: 999
        dispatch-par: 0
        duration-millis: 600000
    crime:
        name: "Crime"
        description: "Lawbreakers are afoot in %dipp_district_name%! Stop them!"
        icon-material: "music_disc_cat"
        icon-custom-model-data: 2
        dispatch-cap: 2
        dispatch-par: 2
        duration-millis: 600000
    fire:
        name: "Fire Fighting"
        description: "%sneakycharacters_character_name% has reported a fire breaking out in %dipp_district_name%!"
        icon-material: "music_disc_cat"
        icon-custom-model-data: 3
        dispatch-cap: 999
        dispatch-par: 4
        duration-millis: 600000
    attack:
        name: "Monster Attack"
        description: "%sneakycharacters_character_name% has reported a Monster Attack in %dipp_district_name%! Suit up, Paladin!"
        icon-material: "music_disc_cat"
        icon-custom-model-data: 4
        dispatch-cap: 999
        dispatch-par: 4
        duration-millis: 600000
    hazard:
        name: "Hazardous Situation"
        description: "%sneakycharacters_character_name% has reported a hazardous situation in %dipp_district_name%! Protect the people!"
        icon-material: "music_disc_cat"
        icon-custom-model-data: 5
        dispatch-cap: 2
        dispatch-par: 1
        duration-millis: 600000
    wildlife:
        name: "Wildlife Control"
        description: "%sneakycharacters_character_name% has reported that wild animals are disturbing our way of life in %dipp_district_name%!"
        icon-material: "music_disc_cat"
        icon-custom-model-data: 6
        dispatch-cap: 2
        dispatch-par: 1
        duration-millis: 600000